export default [
  {
    login: "gabumoh",
    id: 31133984,
    node_id: "MDQ6VXNlcjMxMTMzOTg0",
    avatar_url: "https://avatars.githubusercontent.com/u/31133984?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/gabumoh",
    html_url: "https://github.com/gabumoh",
    followers_url: "https://api.github.com/users/gabumoh/followers",
    following_url:
      "https://api.github.com/users/gabumoh/following{/other_user}",
    gists_url: "https://api.github.com/users/gabumoh/gists{/gist_id}",
    starred_url: "https://api.github.com/users/gabumoh/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/gabumoh/subscriptions",
    organizations_url: "https://api.github.com/users/gabumoh/orgs",
    repos_url: "https://api.github.com/users/gabumoh/repos",
    events_url: "https://api.github.com/users/gabumoh/events{/privacy}",
    received_events_url: "https://api.github.com/users/gabumoh/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "babyfaceEasy",
    id: 16900234,
    node_id: "MDQ6VXNlcjE2OTAwMjM0",
    avatar_url: "https://avatars.githubusercontent.com/u/16900234?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/babyfaceEasy",
    html_url: "https://github.com/babyfaceEasy",
    followers_url: "https://api.github.com/users/babyfaceEasy/followers",
    following_url:
      "https://api.github.com/users/babyfaceEasy/following{/other_user}",
    gists_url: "https://api.github.com/users/babyfaceEasy/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/babyfaceEasy/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/babyfaceEasy/subscriptions",
    organizations_url: "https://api.github.com/users/babyfaceEasy/orgs",
    repos_url: "https://api.github.com/users/babyfaceEasy/repos",
    events_url: "https://api.github.com/users/babyfaceEasy/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/babyfaceEasy/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "mykeels",
    id: 11996508,
    node_id: "MDQ6VXNlcjExOTk2NTA4",
    avatar_url: "https://avatars.githubusercontent.com/u/11996508?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/mykeels",
    html_url: "https://github.com/mykeels",
    followers_url: "https://api.github.com/users/mykeels/followers",
    following_url:
      "https://api.github.com/users/mykeels/following{/other_user}",
    gists_url: "https://api.github.com/users/mykeels/gists{/gist_id}",
    starred_url: "https://api.github.com/users/mykeels/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/mykeels/subscriptions",
    organizations_url: "https://api.github.com/users/mykeels/orgs",
    repos_url: "https://api.github.com/users/mykeels/repos",
    events_url: "https://api.github.com/users/mykeels/events{/privacy}",
    received_events_url: "https://api.github.com/users/mykeels/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "thenameisdrey",
    id: 31135209,
    node_id: "MDQ6VXNlcjMxMTM1MjA5",
    avatar_url: "https://avatars.githubusercontent.com/u/31135209?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/thenameisdrey",
    html_url: "https://github.com/thenameisdrey",
    followers_url: "https://api.github.com/users/thenameisdrey/followers",
    following_url:
      "https://api.github.com/users/thenameisdrey/following{/other_user}",
    gists_url: "https://api.github.com/users/thenameisdrey/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/thenameisdrey/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/thenameisdrey/subscriptions",
    organizations_url: "https://api.github.com/users/thenameisdrey/orgs",
    repos_url: "https://api.github.com/users/thenameisdrey/repos",
    events_url: "https://api.github.com/users/thenameisdrey/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/thenameisdrey/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "iamhabbeboy",
    id: 17249473,
    node_id: "MDQ6VXNlcjE3MjQ5NDcz",
    avatar_url: "https://avatars.githubusercontent.com/u/17249473?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/iamhabbeboy",
    html_url: "https://github.com/iamhabbeboy",
    followers_url: "https://api.github.com/users/iamhabbeboy/followers",
    following_url:
      "https://api.github.com/users/iamhabbeboy/following{/other_user}",
    gists_url: "https://api.github.com/users/iamhabbeboy/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/iamhabbeboy/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/iamhabbeboy/subscriptions",
    organizations_url: "https://api.github.com/users/iamhabbeboy/orgs",
    repos_url: "https://api.github.com/users/iamhabbeboy/repos",
    events_url: "https://api.github.com/users/iamhabbeboy/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/iamhabbeboy/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "InduprasadSR",
    id: 12188140,
    node_id: "MDQ6VXNlcjEyMTg4MTQw",
    avatar_url: "https://avatars.githubusercontent.com/u/12188140?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/InduprasadSR",
    html_url: "https://github.com/InduprasadSR",
    followers_url: "https://api.github.com/users/InduprasadSR/followers",
    following_url:
      "https://api.github.com/users/InduprasadSR/following{/other_user}",
    gists_url: "https://api.github.com/users/InduprasadSR/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/InduprasadSR/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/InduprasadSR/subscriptions",
    organizations_url: "https://api.github.com/users/InduprasadSR/orgs",
    repos_url: "https://api.github.com/users/InduprasadSR/repos",
    events_url: "https://api.github.com/users/InduprasadSR/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/InduprasadSR/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "jilh",
    id: 22137076,
    node_id: "MDQ6VXNlcjIyMTM3MDc2",
    avatar_url: "https://avatars.githubusercontent.com/u/22137076?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/jilh",
    html_url: "https://github.com/jilh",
    followers_url: "https://api.github.com/users/jilh/followers",
    following_url: "https://api.github.com/users/jilh/following{/other_user}",
    gists_url: "https://api.github.com/users/jilh/gists{/gist_id}",
    starred_url: "https://api.github.com/users/jilh/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/jilh/subscriptions",
    organizations_url: "https://api.github.com/users/jilh/orgs",
    repos_url: "https://api.github.com/users/jilh/repos",
    events_url: "https://api.github.com/users/jilh/events{/privacy}",
    received_events_url: "https://api.github.com/users/jilh/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "roccijocci",
    id: 13760632,
    node_id: "MDQ6VXNlcjEzNzYwNjMy",
    avatar_url: "https://avatars.githubusercontent.com/u/13760632?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/roccijocci",
    html_url: "https://github.com/roccijocci",
    followers_url: "https://api.github.com/users/roccijocci/followers",
    following_url:
      "https://api.github.com/users/roccijocci/following{/other_user}",
    gists_url: "https://api.github.com/users/roccijocci/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/roccijocci/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/roccijocci/subscriptions",
    organizations_url: "https://api.github.com/users/roccijocci/orgs",
    repos_url: "https://api.github.com/users/roccijocci/repos",
    events_url: "https://api.github.com/users/roccijocci/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/roccijocci/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "nebanat",
    id: 24405172,
    node_id: "MDQ6VXNlcjI0NDA1MTcy",
    avatar_url: "https://avatars.githubusercontent.com/u/24405172?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/nebanat",
    html_url: "https://github.com/nebanat",
    followers_url: "https://api.github.com/users/nebanat/followers",
    following_url:
      "https://api.github.com/users/nebanat/following{/other_user}",
    gists_url: "https://api.github.com/users/nebanat/gists{/gist_id}",
    starred_url: "https://api.github.com/users/nebanat/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/nebanat/subscriptions",
    organizations_url: "https://api.github.com/users/nebanat/orgs",
    repos_url: "https://api.github.com/users/nebanat/repos",
    events_url: "https://api.github.com/users/nebanat/events{/privacy}",
    received_events_url: "https://api.github.com/users/nebanat/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "ofonimefrancis",
    id: 26252218,
    node_id: "MDQ6VXNlcjI2MjUyMjE4",
    avatar_url: "https://avatars.githubusercontent.com/u/26252218?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/ofonimefrancis",
    html_url: "https://github.com/ofonimefrancis",
    followers_url: "https://api.github.com/users/ofonimefrancis/followers",
    following_url:
      "https://api.github.com/users/ofonimefrancis/following{/other_user}",
    gists_url: "https://api.github.com/users/ofonimefrancis/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/ofonimefrancis/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/ofonimefrancis/subscriptions",
    organizations_url: "https://api.github.com/users/ofonimefrancis/orgs",
    repos_url: "https://api.github.com/users/ofonimefrancis/repos",
    events_url: "https://api.github.com/users/ofonimefrancis/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/ofonimefrancis/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "tonyalaribe",
    id: 6564482,
    node_id: "MDQ6VXNlcjY1NjQ0ODI=",
    avatar_url: "https://avatars.githubusercontent.com/u/6564482?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/tonyalaribe",
    html_url: "https://github.com/tonyalaribe",
    followers_url: "https://api.github.com/users/tonyalaribe/followers",
    following_url:
      "https://api.github.com/users/tonyalaribe/following{/other_user}",
    gists_url: "https://api.github.com/users/tonyalaribe/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/tonyalaribe/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/tonyalaribe/subscriptions",
    organizations_url: "https://api.github.com/users/tonyalaribe/orgs",
    repos_url: "https://api.github.com/users/tonyalaribe/repos",
    events_url: "https://api.github.com/users/tonyalaribe/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/tonyalaribe/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "VictoryOkhormhe",
    id: 41402418,
    node_id: "MDQ6VXNlcjQxNDAyNDE4",
    avatar_url: "https://avatars.githubusercontent.com/u/41402418?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/VictoryOkhormhe",
    html_url: "https://github.com/VictoryOkhormhe",
    followers_url: "https://api.github.com/users/VictoryOkhormhe/followers",
    following_url:
      "https://api.github.com/users/VictoryOkhormhe/following{/other_user}",
    gists_url: "https://api.github.com/users/VictoryOkhormhe/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/VictoryOkhormhe/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/VictoryOkhormhe/subscriptions",
    organizations_url: "https://api.github.com/users/VictoryOkhormhe/orgs",
    repos_url: "https://api.github.com/users/VictoryOkhormhe/repos",
    events_url: "https://api.github.com/users/VictoryOkhormhe/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/VictoryOkhormhe/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "kamsy",
    id: 23347440,
    node_id: "MDQ6VXNlcjIzMzQ3NDQw",
    avatar_url: "https://avatars.githubusercontent.com/u/23347440?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/kamsy",
    html_url: "https://github.com/kamsy",
    followers_url: "https://api.github.com/users/kamsy/followers",
    following_url: "https://api.github.com/users/kamsy/following{/other_user}",
    gists_url: "https://api.github.com/users/kamsy/gists{/gist_id}",
    starred_url: "https://api.github.com/users/kamsy/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/kamsy/subscriptions",
    organizations_url: "https://api.github.com/users/kamsy/orgs",
    repos_url: "https://api.github.com/users/kamsy/repos",
    events_url: "https://api.github.com/users/kamsy/events{/privacy}",
    received_events_url: "https://api.github.com/users/kamsy/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "radiumrasheed",
    id: 11582800,
    node_id: "MDQ6VXNlcjExNTgyODAw",
    avatar_url: "https://avatars.githubusercontent.com/u/11582800?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/radiumrasheed",
    html_url: "https://github.com/radiumrasheed",
    followers_url: "https://api.github.com/users/radiumrasheed/followers",
    following_url:
      "https://api.github.com/users/radiumrasheed/following{/other_user}",
    gists_url: "https://api.github.com/users/radiumrasheed/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/radiumrasheed/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/radiumrasheed/subscriptions",
    organizations_url: "https://api.github.com/users/radiumrasheed/orgs",
    repos_url: "https://api.github.com/users/radiumrasheed/repos",
    events_url: "https://api.github.com/users/radiumrasheed/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/radiumrasheed/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "kingsleyudenewu",
    id: 8123837,
    node_id: "MDQ6VXNlcjgxMjM4Mzc=",
    avatar_url: "https://avatars.githubusercontent.com/u/8123837?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/kingsleyudenewu",
    html_url: "https://github.com/kingsleyudenewu",
    followers_url: "https://api.github.com/users/kingsleyudenewu/followers",
    following_url:
      "https://api.github.com/users/kingsleyudenewu/following{/other_user}",
    gists_url: "https://api.github.com/users/kingsleyudenewu/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/kingsleyudenewu/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/kingsleyudenewu/subscriptions",
    organizations_url: "https://api.github.com/users/kingsleyudenewu/orgs",
    repos_url: "https://api.github.com/users/kingsleyudenewu/repos",
    events_url: "https://api.github.com/users/kingsleyudenewu/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/kingsleyudenewu/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "BolajiAyodeji",
    id: 30334776,
    node_id: "MDQ6VXNlcjMwMzM0Nzc2",
    avatar_url: "https://avatars.githubusercontent.com/u/30334776?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/BolajiAyodeji",
    html_url: "https://github.com/BolajiAyodeji",
    followers_url: "https://api.github.com/users/BolajiAyodeji/followers",
    following_url:
      "https://api.github.com/users/BolajiAyodeji/following{/other_user}",
    gists_url: "https://api.github.com/users/BolajiAyodeji/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/BolajiAyodeji/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/BolajiAyodeji/subscriptions",
    organizations_url: "https://api.github.com/users/BolajiAyodeji/orgs",
    repos_url: "https://api.github.com/users/BolajiAyodeji/repos",
    events_url: "https://api.github.com/users/BolajiAyodeji/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/BolajiAyodeji/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "blarcmann",
    id: 12191062,
    node_id: "MDQ6VXNlcjEyMTkxMDYy",
    avatar_url: "https://avatars.githubusercontent.com/u/12191062?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/blarcmann",
    html_url: "https://github.com/blarcmann",
    followers_url: "https://api.github.com/users/blarcmann/followers",
    following_url:
      "https://api.github.com/users/blarcmann/following{/other_user}",
    gists_url: "https://api.github.com/users/blarcmann/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/blarcmann/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/blarcmann/subscriptions",
    organizations_url: "https://api.github.com/users/blarcmann/orgs",
    repos_url: "https://api.github.com/users/blarcmann/repos",
    events_url: "https://api.github.com/users/blarcmann/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/blarcmann/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Basitomania",
    id: 29269252,
    node_id: "MDQ6VXNlcjI5MjY5MjUy",
    avatar_url: "https://avatars.githubusercontent.com/u/29269252?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Basitomania",
    html_url: "https://github.com/Basitomania",
    followers_url: "https://api.github.com/users/Basitomania/followers",
    following_url:
      "https://api.github.com/users/Basitomania/following{/other_user}",
    gists_url: "https://api.github.com/users/Basitomania/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Basitomania/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Basitomania/subscriptions",
    organizations_url: "https://api.github.com/users/Basitomania/orgs",
    repos_url: "https://api.github.com/users/Basitomania/repos",
    events_url: "https://api.github.com/users/Basitomania/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Basitomania/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "FunbiOyede",
    id: 38365805,
    node_id: "MDQ6VXNlcjM4MzY1ODA1",
    avatar_url: "https://avatars.githubusercontent.com/u/38365805?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/FunbiOyede",
    html_url: "https://github.com/FunbiOyede",
    followers_url: "https://api.github.com/users/FunbiOyede/followers",
    following_url:
      "https://api.github.com/users/FunbiOyede/following{/other_user}",
    gists_url: "https://api.github.com/users/FunbiOyede/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/FunbiOyede/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/FunbiOyede/subscriptions",
    organizations_url: "https://api.github.com/users/FunbiOyede/orgs",
    repos_url: "https://api.github.com/users/FunbiOyede/repos",
    events_url: "https://api.github.com/users/FunbiOyede/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/FunbiOyede/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Youngestdev",
    id: 31009679,
    node_id: "MDQ6VXNlcjMxMDA5Njc5",
    avatar_url: "https://avatars.githubusercontent.com/u/31009679?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Youngestdev",
    html_url: "https://github.com/Youngestdev",
    followers_url: "https://api.github.com/users/Youngestdev/followers",
    following_url:
      "https://api.github.com/users/Youngestdev/following{/other_user}",
    gists_url: "https://api.github.com/users/Youngestdev/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Youngestdev/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Youngestdev/subscriptions",
    organizations_url: "https://api.github.com/users/Youngestdev/orgs",
    repos_url: "https://api.github.com/users/Youngestdev/repos",
    events_url: "https://api.github.com/users/Youngestdev/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Youngestdev/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "favourch",
    id: 9114705,
    node_id: "MDQ6VXNlcjkxMTQ3MDU=",
    avatar_url: "https://avatars.githubusercontent.com/u/9114705?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/favourch",
    html_url: "https://github.com/favourch",
    followers_url: "https://api.github.com/users/favourch/followers",
    following_url:
      "https://api.github.com/users/favourch/following{/other_user}",
    gists_url: "https://api.github.com/users/favourch/gists{/gist_id}",
    starred_url: "https://api.github.com/users/favourch/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/favourch/subscriptions",
    organizations_url: "https://api.github.com/users/favourch/orgs",
    repos_url: "https://api.github.com/users/favourch/repos",
    events_url: "https://api.github.com/users/favourch/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/favourch/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Umoren",
    id: 22575481,
    node_id: "MDQ6VXNlcjIyNTc1NDgx",
    avatar_url: "https://avatars.githubusercontent.com/u/22575481?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Umoren",
    html_url: "https://github.com/Umoren",
    followers_url: "https://api.github.com/users/Umoren/followers",
    following_url: "https://api.github.com/users/Umoren/following{/other_user}",
    gists_url: "https://api.github.com/users/Umoren/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Umoren/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Umoren/subscriptions",
    organizations_url: "https://api.github.com/users/Umoren/orgs",
    repos_url: "https://api.github.com/users/Umoren/repos",
    events_url: "https://api.github.com/users/Umoren/events{/privacy}",
    received_events_url: "https://api.github.com/users/Umoren/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "UcheSylvester",
    id: 38369717,
    node_id: "MDQ6VXNlcjM4MzY5NzE3",
    avatar_url: "https://avatars.githubusercontent.com/u/38369717?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/UcheSylvester",
    html_url: "https://github.com/UcheSylvester",
    followers_url: "https://api.github.com/users/UcheSylvester/followers",
    following_url:
      "https://api.github.com/users/UcheSylvester/following{/other_user}",
    gists_url: "https://api.github.com/users/UcheSylvester/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/UcheSylvester/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/UcheSylvester/subscriptions",
    organizations_url: "https://api.github.com/users/UcheSylvester/orgs",
    repos_url: "https://api.github.com/users/UcheSylvester/repos",
    events_url: "https://api.github.com/users/UcheSylvester/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/UcheSylvester/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "aosimeon",
    id: 26606891,
    node_id: "MDQ6VXNlcjI2NjA2ODkx",
    avatar_url: "https://avatars.githubusercontent.com/u/26606891?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/aosimeon",
    html_url: "https://github.com/aosimeon",
    followers_url: "https://api.github.com/users/aosimeon/followers",
    following_url:
      "https://api.github.com/users/aosimeon/following{/other_user}",
    gists_url: "https://api.github.com/users/aosimeon/gists{/gist_id}",
    starred_url: "https://api.github.com/users/aosimeon/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/aosimeon/subscriptions",
    organizations_url: "https://api.github.com/users/aosimeon/orgs",
    repos_url: "https://api.github.com/users/aosimeon/repos",
    events_url: "https://api.github.com/users/aosimeon/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/aosimeon/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "jay-i",
    id: 22917214,
    node_id: "MDQ6VXNlcjIyOTE3MjE0",
    avatar_url: "https://avatars.githubusercontent.com/u/22917214?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/jay-i",
    html_url: "https://github.com/jay-i",
    followers_url: "https://api.github.com/users/jay-i/followers",
    following_url: "https://api.github.com/users/jay-i/following{/other_user}",
    gists_url: "https://api.github.com/users/jay-i/gists{/gist_id}",
    starred_url: "https://api.github.com/users/jay-i/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/jay-i/subscriptions",
    organizations_url: "https://api.github.com/users/jay-i/orgs",
    repos_url: "https://api.github.com/users/jay-i/repos",
    events_url: "https://api.github.com/users/jay-i/events{/privacy}",
    received_events_url: "https://api.github.com/users/jay-i/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "techbola",
    id: 19407952,
    node_id: "MDQ6VXNlcjE5NDA3OTUy",
    avatar_url: "https://avatars.githubusercontent.com/u/19407952?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/techbola",
    html_url: "https://github.com/techbola",
    followers_url: "https://api.github.com/users/techbola/followers",
    following_url:
      "https://api.github.com/users/techbola/following{/other_user}",
    gists_url: "https://api.github.com/users/techbola/gists{/gist_id}",
    starred_url: "https://api.github.com/users/techbola/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/techbola/subscriptions",
    organizations_url: "https://api.github.com/users/techbola/orgs",
    repos_url: "https://api.github.com/users/techbola/repos",
    events_url: "https://api.github.com/users/techbola/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/techbola/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "paulayuk",
    id: 23018996,
    node_id: "MDQ6VXNlcjIzMDE4OTk2",
    avatar_url: "https://avatars.githubusercontent.com/u/23018996?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/paulayuk",
    html_url: "https://github.com/paulayuk",
    followers_url: "https://api.github.com/users/paulayuk/followers",
    following_url:
      "https://api.github.com/users/paulayuk/following{/other_user}",
    gists_url: "https://api.github.com/users/paulayuk/gists{/gist_id}",
    starred_url: "https://api.github.com/users/paulayuk/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/paulayuk/subscriptions",
    organizations_url: "https://api.github.com/users/paulayuk/orgs",
    repos_url: "https://api.github.com/users/paulayuk/repos",
    events_url: "https://api.github.com/users/paulayuk/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/paulayuk/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "femicodes",
    id: 20581468,
    node_id: "MDQ6VXNlcjIwNTgxNDY4",
    avatar_url: "https://avatars.githubusercontent.com/u/20581468?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/femicodes",
    html_url: "https://github.com/femicodes",
    followers_url: "https://api.github.com/users/femicodes/followers",
    following_url:
      "https://api.github.com/users/femicodes/following{/other_user}",
    gists_url: "https://api.github.com/users/femicodes/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/femicodes/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/femicodes/subscriptions",
    organizations_url: "https://api.github.com/users/femicodes/orgs",
    repos_url: "https://api.github.com/users/femicodes/repos",
    events_url: "https://api.github.com/users/femicodes/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/femicodes/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Tiemma",
    id: 14789630,
    node_id: "MDQ6VXNlcjE0Nzg5NjMw",
    avatar_url: "https://avatars.githubusercontent.com/u/14789630?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Tiemma",
    html_url: "https://github.com/Tiemma",
    followers_url: "https://api.github.com/users/Tiemma/followers",
    following_url: "https://api.github.com/users/Tiemma/following{/other_user}",
    gists_url: "https://api.github.com/users/Tiemma/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Tiemma/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Tiemma/subscriptions",
    organizations_url: "https://api.github.com/users/Tiemma/orgs",
    repos_url: "https://api.github.com/users/Tiemma/repos",
    events_url: "https://api.github.com/users/Tiemma/events{/privacy}",
    received_events_url: "https://api.github.com/users/Tiemma/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "hashDanChibueze",
    id: 34796665,
    node_id: "MDQ6VXNlcjM0Nzk2NjY1",
    avatar_url: "https://avatars.githubusercontent.com/u/34796665?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/hashDanChibueze",
    html_url: "https://github.com/hashDanChibueze",
    followers_url: "https://api.github.com/users/hashDanChibueze/followers",
    following_url:
      "https://api.github.com/users/hashDanChibueze/following{/other_user}",
    gists_url: "https://api.github.com/users/hashDanChibueze/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/hashDanChibueze/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/hashDanChibueze/subscriptions",
    organizations_url: "https://api.github.com/users/hashDanChibueze/orgs",
    repos_url: "https://api.github.com/users/hashDanChibueze/repos",
    events_url: "https://api.github.com/users/hashDanChibueze/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/hashDanChibueze/received_events",
    type: "User",
    site_admin: false,
  },
];
