export default {
  login: "ElizabethdevQueen",
  id: 66387727,
  node_id: "MDQ6VXNlcjY2Mzg3NzI3",
  avatar_url: "https://avatars.githubusercontent.com/u/66387727?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/ElizabethdevQueen",
  html_url: "https://github.com/ElizabethdevQueen",
  followers_url: "https://api.github.com/users/ElizabethdevQueen/followers",
  following_url:
    "https://api.github.com/users/ElizabethdevQueen/following{/other_user}",
  gists_url: "https://api.github.com/users/ElizabethdevQueen/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/ElizabethdevQueen/starred{/owner}{/repo}",
  subscriptions_url:
    "https://api.github.com/users/ElizabethdevQueen/subscriptions",
  organizations_url: "https://api.github.com/users/ElizabethdevQueen/orgs",
  repos_url: "https://api.github.com/users/ElizabethdevQueen/repos",
  events_url: "https://api.github.com/users/ElizabethdevQueen/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/ElizabethdevQueen/received_events",
  type: "User",
  site_admin: false,
  name: "Elizabeth O. Segun-Ajiboye",
  company: null,
  blog: "",
  location: "Lagos, Nigeria",
  email: null,
  hireable: null,
  bio: "Growth is sacrosanct. ",
  twitter_username: "elizadevqueen",
  public_repos: 38,
  public_gists: 0,
  followers: 1,
  following: 5,
  created_at: "2020-06-03T20:00:15Z",
  updated_at: "2021-05-02T18:49:40Z",
};
